// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID        int      `json:"id"`
	Slug      string   `json:"slug"`
	Title     string   `json:"title"`
	Body      string   `json:"body"`
	Author    *User    `json:"author"`
	Tags      []string `json:"tags"`
	CreatedAt string   `json:"createdAt"`
	Category  string   `json:"category"`
}

type PostData struct {
	ID       int      `json:"id"`
	Title    string   `json:"title"`
	Body     string   `json:"body"`
	Tags     []string `json:"tags"`
	Category string   `json:"category"`
}

type User struct {
	Name      string `json:"name"`
	Image     string `json:"image"`
	CreatedAt string `json:"createdAt"`
}
